lesson7+/core/urls.py
from django.urls import path
from core import views

app_name = 'core'


urlpatterns = [
    path('', views.NewList.as_view(), name='list_news'),
    path('new/<int:pk>', views.NewDetail.as_view(), name='detail_new'),
    path('about/', views.about, name='about'),
    path('new_create/', views.NewCreate.as_view(), name='new_create'),
    path('new_update/<int:pk>', views.NewUpdate.as_view(), name='new_update'),
    path('new_delete/<int:pk>', views.NewDelete.as_view(), name='new_delete'),
]

lesson7+/edu/urls.py
from django.urls import path
from edu import views


app_name = 'edu'


urlpatterns = [
    path('list_tests/', views.TestList.as_view(), name='list_tests'),
    path('list_tasks/', views.TaskList.as_view(), name='list_tasks'),
    path('test/<int:pk>', views.TestDetail.as_view(), name='detail_test'),
    path('task/<int:pk>', views.TaskDetail.as_view(), name='detail_task'),
    path('task_create/', views.TaskCreate.as_view(), name='task_create'),
    path('task_update/<int:pk>', views.TaskUpdate.as_view(), name='task_update'),
    path('task_delete/<int:pk>', views.TaskDelete.as_view(), name='task_delete'),
    path('test_create/', views.TestCreateView.as_view(), name='test_create'),
]

lesson7+/project/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('core.urls'), name='core'),
    path('edu/', include('edu.urls'), name='edu'),
    path('users/', include('users.urls'), name='users'),
]

lesson7+/users/urls.py
from django.urls import path
from users.views import profile, LoginView, logout_view, register_view, ProfileUpdate

app_name = 'users'


urlpatterns = [
    path('profile/<slug:slug>', profile, name='profile'),
    path('login/', LoginView.as_view(), name='login'),
    path('logout/', logout_view, name='logout'),
    path('register/', register_view, name='register'),
    path('profile_update/<slug:slug>', ProfileUpdate.as_view(), name='profile_update'),
]

lesson7+/templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <link rel="stylesheet" href="{% static 'css/style.css' %}" type="text/css">
    <title>{% block title %}Заголовок страницы{% endblock%}</title>
</head>
<body>

    <div class="main-content" style="background-image: url({% static 'image/back_base.jpg'%})";>
        <nav class="menu">
            <div class="group">
                <img class="logo" src="{% static 'image/logo.png' %}" alt="Логотип">
                <div class="group1">
                    <a href="{% url 'core:list_news' %}">Главная</a>
                    <a href="{% url 'core:about'%}">О себе</a>
                    <a href="{% url 'edu:list_tests' %}">Список готовых тестов</a>
                    <a href="{% url 'edu:list_tasks' %}">Каталог заданий</a>
                    <a href="#">Обратная связь</a>
                </div>
            </div>
            <div class="group">
                {% if request.user.is_authenticated %}
                    <p><a href="{% url 'users:profile' slug=request.user.username %}">{{ request.user.first_name }}</a> | <a href="{% url 'users:logout' %}">выйти</a></p>
                {% else %}
                    <p><a href="{% url 'users:register' %}">зарегистрироваться</a> | <a href="{% url 'users:login' %}">войти</a></p>
                    <!--<p><button type="button" onclick="openForm('myForm1')">Регистрация</button> | <button type="button" onclick="openForm('myForm')">Войти</button> </p>-->
                {% endif %}
            </div>
        </nav>
        <div class="main-content-element">
            <div class="left-panel">
                {% block filters %}{% endblock%}
            </div>
            <div>
            {% block content%}
                Тут будет содержание страницы
            {% endblock%}

            </div>
        </div>


       <!--<div class="form_auth_block" id="myForm" style="background-image: url({% static 'image/logo.png'%})";>
          <div class="form_auth_block_content">
            <p class="form_auth_block_head_text">Авторизация</p>
            <form class="form_auth_style" action="{% url 'users:login' %}" method="post">
              {% csrf_token %}
              <label>Введите имя пользователя</label>
              <input type="text" name="username" placeholder="Введите имя пользователя" required >
              <label>Введите пароль</label>
              <input type="password" name="password" placeholder="Введите пароль" required >
              <input type="hidden" name="lastpath" value="{{request.path}}">
              <input type="hidden" name="name_form" value="auth_form">
              <button class="form_auth_button" type="submit" name="form_auth">Войти</button>
              <button class="form_auth_button" type="button" onclick="closeForm('myForm')">Отмена</button>
            </form>
          </div>
        </div>
       <div class="form_auth_block" id="myForm1" style="background-image: url({% static 'image/back_reg.jpg'%})";>
          <div class="form_auth_block_content">
            <p class="form_auth_block_head_text">Регистрация</p>
            <form class="form_auth_style" action="{% url 'users:register' %}" method="post">
              {% csrf_token %}
              <label>Введите имя пользователя</label>
              <input type="text" name="username" placeholder="Введите имя пользователя" required >
              <label>Введите Ваше имя</label>
              <input type="text" name="first_name" placeholder="Введите Ваше имя" required >
              <label>Введите Вашу фамилию</label>
              <input type="text" name="last_name" placeholder="Введите Вашу фамилию" required >
              <label>Введите пароль</label>
              <input type="password" name="password1" placeholder="Введите пароль" required >
              <label>Повторите пароль</label>
              <input type="password" name="password2" placeholder="Повторите пароль" required >
              <label>Введите Ваш город</label>
              <input type="text" name="city" placeholder="Введите Ваш город" required >
              <label>Введите Вашу школу</label>
              <input type="text" name="school" placeholder="Введите Вашу школу" required >
              <label>Введите класс</label>
              <input type="number" name="grade" placeholder="Введите класс" required >
              <input type="hidden" name="lastpath" value="{{request.path}}">
              <input type="hidden" name="name_form" value="reg_form">
              <button class="form_auth_button" type="submit">Зарегистрироваться</button>
              <button class="form_auth_button" type="button" onclick="closeForm('myForm1')">Отмена</button>
            </form>
          </div>
        </div>
       <script src="{% static 'js/auth_form.js' %}"></script>-->


    </div>



</body>
</html>