lesson7+/edu/urls.py
from django.urls import path
from edu import views


app_name = 'edu'


urlpatterns = [
    path('list_tests/', views.TestList.as_view(), name='list_tests'),
    path('list_tasks/', views.TaskList.as_view(), name='list_tasks'),
    path('test/<int:pk>', views.TestDetail.as_view(), name='detail_test'),
    path('task/<int:pk>', views.TaskDetail.as_view(), name='detail_task'),
    path('task_create/', views.TaskCreate.as_view(), name='task_create'),
    path('task_update/<int:pk>', views.TaskUpdate.as_view(), name='task_update'),
    path('task_delete/<int:pk>', views.TaskDelete.as_view(), name='task_delete'),
    path('test_create/', views.TestCreateView.as_view(), name='test_create'),
]

lesson7+/project/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('core.urls'), name='core'),
    path('edu/', include('edu.urls'), name='edu'),
    path('users/', include('users.urls'), name='users'),
]

lesson7+/edu/models.py
from django.db import models




class Task(models.Model):
    task = models.CharField(max_length=1000, verbose_name='Условие')
    answer = models.CharField(max_length=100, verbose_name='Правильный ответ')
    section = models.ForeignKey('Section', on_delete=models.CASCADE, verbose_name='Раздел', related_name='tasks')

    def __str__(self):
        return 'Задание №:{num}, раздел {section}'.format(
            section=self.section,
            num=self.pk
        )

    class Meta:
        verbose_name = 'Задание'
        verbose_name_plural = 'Задания'


class Test(models.Model):
    title = models.CharField(max_length=100, verbose_name='Тема теста')
    tasks_list = models.ManyToManyField('Task', related_name='tasks')

    def __str__(self):
        return 'Тема: {title}, количесво задани {cnt_task}'.format(
            title=self.title,
            cnt_task=len(self.tasks_list.all())
        )

    class Meta:
        verbose_name = 'Тест'
        verbose_name_plural = 'Тесты'


class Section(models.Model):
    title = models.CharField(max_length=200, verbose_name='Раздел')

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = 'Раздел'
        verbose_name_plural = 'Разделы'

class Answer(models.Model):
    answer = models.CharField(max_length=100, verbose_name='Ответ')
    task = models.ForeignKey('Task', on_delete=models.CASCADE, verbose_name='Задача', related_name='answers')
    test = models.ForeignKey('Test', on_delete=models.CASCADE, verbose_name='Тест', related_name='answers', blank=True, null=True)
    status = models.BooleanField(verbose_name='статус', default=False)

    def __str__(self):
        return 'Задание №{num}: ваш ответ {answer}. Статус {status}'.format(
            answer=self.answer,
            num=self.task.pk,
            status = 'решено' if self.status else 'нерешено'
        )

lesson7+/edu/forms.py
from edu import models
from django import forms

class TaskForm(forms.ModelForm):
    class Meta:
        model = models.Task
        fields = ["task", "answer", "section"]

lesson7+/edu/views.py
from django.shortcuts import render, redirect
from django.urls import reverse_lazy, reverse
from django.views.generic import ListView, DetailView, CreateView, UpdateView, DeleteView, View
from edu import models
from edu import filters
from edu import forms


class TitleMixin():
    title = None

    def get_title(self):
        return self.title

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = self.get_title()
        return context


class TestList(TitleMixin, ListView):
    model = models.Test
    template_name = 'edu/list_tests.html'
    context_object_name = 'tests'
    title = 'Каталог тестов'

    def get_filters(self):
        return filters.TestFilter(self.request.GET)

    def get_queryset(self):
        return self.get_filters().qs

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['filters'] = self.get_filters()
        return context


class TaskList(TitleMixin, ListView):
    model = models.Task
    template_name = 'edu/list_tasks.html'
    context_object_name = 'tasks'
    title = 'Каталог заданий'

    def get_filters(self):
        return filters.TaskFilter(self.request.GET)
    
    def get_queryset(self):
        return self.get_filters().qs
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['filters'] = self.get_filters()
        return context


class TestDetail(DetailView):
    model = models.Test
    template_name = 'edu/detail_test.html'
    context_object_name = 'test'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = context['object'].title
        return context


class TaskDetail(DetailView):
    model = models.Task
    template_name = 'edu/detail_task.html'
    context_object_name = 'task'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = context['object'].__str__()
        return context


class TaskCreate(CreateView):
    model = models.Task
    template_name = 'edu/task_create.html'
    fields = '__all__'
    title = 'Создание задачи'
    success_url = reverse_lazy("edu:list_tasks")


class TaskUpdate(TitleMixin, UpdateView):
    model = models.Task
    template_name = 'edu/task_update.html'
    fields = '__all__'
    title = 'Изменение задачи'

    def get_success_url(self):
        return reverse_lazy("edu:detail_task", kwargs={'pk': self.object.pk})


class TaskDelete(TitleMixin, DeleteView):
    model = models.Task
    template_name = 'edu/task_delete.html'
    title = 'Удаление задачи'
    success_url = reverse_lazy("edu:list_tasks")


class TestCreateView(View):
    def post(self, request):
        if request.POST.get('create_test'):
            list_task_id = dict(request.POST).get('list_task_id')
            if list_task_id:
                new_test = models.Test.objects.create(title=request.POST["title"])
                new_test.tasks_list.set(models.Task.objects.filter(pk__in=list_task_id))
                print(new_test)
                return redirect(reverse('edu:detail_test', kwargs={'pk': new_test.pk}))
        context = self.get_context_data(request)
        if request.POST.get('create_task'):
            new_task = models.Task.objects.create(
                task=request.POST.get('task'),
                answer=request.POST.get('answer'),
                section_id=int(request.POST.get('section'))
            )
            context['list_task_id'].append(str(new_task.pk))
        if request.POST.get('add_task'):
            form = forms.TaskForm()
            context['form_task'] = form
        return render(request, 'edu/test_create.html', context=context)

    def get(self, request):
        context = self.get_context_data(request)
        return render(request, 'edu/test_create.html', context=context)

    def get_filters(self):
        return filters.TaskFilter(self.request.GET)

    def get_queryset(self):
        return self.get_filters().qs

    def get_context_data(self, request):
        context = {'tasks': self.get_queryset(),
                   'filters': self.get_filters(),
                   'title': 'Создание теста',
                   'list_task_id': dict(request.POST).get('list_task_id', [])}
        return context

lesson7+/templates/edu/detail_task.html
{% extends "base.html" %}

{% block title %} {{title}} {% endblock%}

{% block content%}
    {% if task %}
        <div>
            <p>id задачи: {{task.pk}}</p>
            <p>раздел: {{task.section}}</p>
            <p>условие: {{task.task}}</p>
        </div>
    {% else %}
        <div>
            <p>Что то пошло не так, вернитесь к списку задач</p>
        </div>
    {% endif %}

    <div>
        {% if request.user.is_superuser %}
            <a href="{% url 'edu:task_update' pk=task.pk%}">Обновить задачу</a>
            <a href="{% url 'edu:task_delete' pk=task.pk%}">Удалить задачу</a>
        {% endif %}
        <a href="{% url 'edu:list_tasks' %}">Назад к катологу заданий</a>
    </div>
{% endblock%}

lesson7+/templates/edu/detail_test.html
{% extends "base.html" %}

{% block title %} {{title}} {% endblock%}

{% block content%}
    {% if test %}
        {% for task in test.tasks_list.all %}
            <div>
                <p>id задачи: {{task.pk}}</p>
                <p>условие: {{task.task}}</p>
            </div>
        {% endfor %}
    {% else %}
        <div>
            <p>Что то пошло не так, вернитесь к списку тестов</p>
        </div>
    {% endif %}
    <div>
        {% if request.user.is_superuser %}
            <a href="#">Обновить тест</a>
            <a href="#">Удалить тест</a>
        {% endif %}
        <a href="{% url 'edu:list_tests' %}">Назад к списку тестов</a>
    </div>
{% endblock%}

lesson7+/templates/edu/list_task.html
{% extends "base.html" %}

{% block title %} Заголовок страницы {% endblock%}

{% block content%}
    <h1>Тут будет список задач</h1>
{% endblock%}

lesson7+/templates/edu/list_tasks.html
{% extends "base.html" %}

{% block title %} {{title}} {% endblock%}

{% block content%}
    {% for task in tasks %}
        <div>
            <p><a href="{% url 'edu:detail_task' pk=task.pk %}">{{task}}</a></p>
            <p>{{task.task}}</p>
        </div>

    {% empty %}
        <p>список задач пуст</p>
    {% endfor %}
    {% if request.user.is_superuser %}
        <a href="{% url 'edu:task_create' %}">Добавить задачу</a>
    {% endif %}
{% endblock%}

{% block filters %}
<form action="{% url 'edu:list_tasks' %}" method="GET">
    {% csrf_token %}
    {{ filters.form.as_p }}
    <button type="submit">Найти</button>
</form>
{% endblock%}

lesson7+/templates/edu/list_tests.html
{% extends "base.html" %}

{% block title %} {{title}} {% endblock%}

{% block content %}
    {% if tests %}
        {% for test in tests %}
            <p><a href="{% url 'edu:detail_test' pk=test.pk %}">{{test}}</a></p>
        {% endfor %}
    {% else %}
        список тестов пуст
    {% endif %}
    {% if request.user.is_superuser %}
        <a href="{% url 'edu:test_create' %}">Добавить тест</a>
    {% endif %}
{% endblock %}

{% block filters %}
<form action="{% url 'edu:list_tests' %}" method="GET">
    {% csrf_token %}
    {{ filters.form.as_p }}
    <button type="submit">Найти</button>
</form>
{% endblock %}

lesson7+/templates/edu/task_create.html
{% extends "base.html" %}

{% block title %} {{title}} {% endblock%}

{% block content%}
<form action="" method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Сохранить</button>
    <button type="reset">Очистить</button>
</form>
<form action="{% url 'edu:list_tasks' %}"><button type="submit">Отменить</button></form>
{% endblock%}

lesson7+/templates/edu/task_delete.html
{% extends "base.html" %}

{% block title %} {{title}} {% endblock%}

{% block content%}
<form action="" method="post">
    {% csrf_token %}
    {{ form }}
    <p>Вы действительно хотите удалить {{task}}</p>
    <button type="submit">Удалить</button>
</form>
<form action="{% url 'edu:list_tasks' %}"><button type="submit">Отменить</button></form>
{% endblock%}

lesson7+/templates/edu/task_update.html
{% extends "base.html" %}

{% block title %} {{title}} {% endblock%}

{% block content%}
<form action="" method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Обновить</button>
    <button type="reset">Сбросить изменения</button>
</form>
<form action="{% url 'edu:detail_task' pk=task.pk %}"><button type="submit">Отменить</button></form>
{% endblock%}

lesson7+/templates/edu/test_create.html
{% extends "base.html" %}

{% block title %} {{title}} {% endblock%}

{% block content%}
    {% load edu_tags %}
    <h1>Создать тест:</h1>

    <form method="post">
      {% csrf_token %}
        <p><label>Введите название теста:</label></p>
        <p><input type="text" name="title" required ></p>
        <p>Выберите задания. Слева можно отфильтровать задания по разделам.</p>
        {% for task in tasks %}
        <p><input type="checkbox" value="{{task.id}}" name="list_task_id" {% get_checked task.pk list_task_id %}>id задачи: {{task.pk}}</p>
        <p>{{task.task}}</p>
        {% empty %}
          <p>По вашему запросу задач рне найдено. Провторите поиск</p>
        {% endfor %}
        {% if form_task %}
            <p>Добавление задачи</p>
            {{ form_task.as_p }}
            <button type="submit" name="create_task" value="1">Сохранить задачу</button>
        {% else %}
            <button type="submit" name="add_task" value="1">добавить задачу</button>
        {% endif %}
      <button type="submit" name="create_test" value="1">Сохранить тест</button>
    </form>
    <form action="{% url 'edu:list_tests' %}"><button type="submit">К списку тестов</button></form>

{% endblock%}

{% block filters %}
<p>Фильтр задач:</p>
<form action="{% url 'edu:test_create' %}" method="GET">
    {% csrf_token %}
    {{ filters.form.as_p }}
    <button type="submit">Найти</button>
</form>
{% endblock%}