lesson7+/edu/urls.py
from django.urls import path
from edu import views


app_name = 'edu'


urlpatterns = [
    path('list_tests/', views.TestList.as_view(), name='list_tests'),
    path('list_tasks/', views.TaskList.as_view(), name='list_tasks'),
    path('test/<int:pk>', views.TestDetail.as_view(), name='detail_test'),
    path('task/<int:pk>', views.TaskDetail.as_view(), name='detail_task'),
    path('task_create/', views.TaskCreate.as_view(), name='task_create'),
    path('task_update/<int:pk>', views.TaskUpdate.as_view(), name='task_update'),
    path('task_delete/<int:pk>', views.TaskDelete.as_view(), name='task_delete'),
    path('test_create/', views.TestCreateView.as_view(), name='test_create'),
]

lesson7+/project/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('core.urls'), name='core'),
    path('edu/', include('edu.urls'), name='edu'),
    path('users/', include('users.urls'), name='users'),
]

lesson7+/users/urls.py
from django.urls import path
from users.views import profile, LoginView, logout_view, register_view, ProfileUpdate

app_name = 'users'


urlpatterns = [
    path('profile/<slug:slug>', profile, name='profile'),
    path('login/', LoginView.as_view(), name='login'),
    path('logout/', logout_view, name='logout'),
    path('register/', register_view, name='register'),
    path('profile_update/<slug:slug>', ProfileUpdate.as_view(), name='profile_update'),
]

lesson7+/users/models.py
from django.contrib.auth.models import User
from django.db import models
from django.urls import reverse

class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    slug = models.SlugField(max_length=40, unique=True, db_index=True, verbose_name='url')
    city = models.CharField(max_length=40, blank=True, verbose_name='Город проживания')
    school = models.CharField(max_length=200, blank=True, verbose_name='Школа')
    grade = models.IntegerField(default=0, blank=True, verbose_name='Класс')
    tests = models.ManyToManyField('edu.Test', blank=True, verbose_name='Тесты')

    def get_absolute_url(self):
        return reverse('profile', kwargs={'profile_slug': self.slug})

    def __str__(self):
        return "{name} {second_name}".format(
            name=self.user.first_name,
            second_name=self.user.last_name
        )

    class Meta:
        verbose_name = 'Профиль ользователя'
        verbose_name_plural = 'Профили пользователей'

lesson7+/users/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User


class AuthUser(forms.Form):
    username = forms.CharField(max_length=20)
    password = forms.CharField(widget=forms.PasswordInput)


class RegisterForm(UserCreationForm):
    username = forms.CharField(max_length=20, required=False, label='Имя пользователя')
    first_name = forms.CharField(max_length=20, required=False, label='Имя')
    last_name = forms.CharField(max_length=20, required=False, label='Фамилия')
    slug = forms.CharField(max_length=20, required=False, help_text='только латинские буквы и цифры')
    city = forms.CharField(required=False, label='Город')
    school = forms.CharField(required=False, label='Школа')
    grade = forms.IntegerField(required=False, label='Класс', help_text='Только число, без букв')
    slug.widget = slug.hidden_widget()

    def clean_username(self):
        name = self.cleaned_data['username']
        if not all([let.isdigit() or let in '-_' or ord('A') <= ord(let) <= ord('z') for let in name]):
            raise forms.ValidationError('Имя пользователя может содержать только латинские буквы, цифры - и _')
        return name

    class Meta:
        model = User
        fields = ('username', 'first_name', 'last_name', 'password1', 'password2',)

lesson7+/users/views.py
from django.contrib.auth import login, authenticate, logout
from django.urls import reverse_lazy
from django.views import View
from django.views.generic import UpdateView
from users.models import Profile
from users.forms import RegisterForm, AuthUser

from django.contrib.auth.models import User
from django.shortcuts import render, get_object_or_404, redirect


def profile(request, slug):
    profile = get_object_or_404(Profile, slug=slug)
    context = {
        'profile': profile,
        'title': profile.__str__()
    }
    return render(request, 'users/profile.html', context=context)

def logout_view(request):
    logout(request)
    return redirect('/')

class LoginView(View):
    def get(self, request):
        form = AuthUser()
        context = {'form': form}
        return render(request, 'users/auth_user.html', context=context)

    def post(self, request):
        form = AuthUser(request.POST)
        if form.is_valid():
            username = form.cleaned_data['username']
            password = form.cleaned_data['password']
            user = authenticate(username=username, password=password)
            if user:
                if user.is_active:
                    login(request, user)
                    return redirect('/')
                else:
                    form.add_error('__all__', 'Учетная запись не активна.')
            else:
                form.add_error('__all__', 'Неверно введены имя пользователя или пароль.')
        context = {'form': form, 'title': 'авторизация пользователя'}
        return render(request, 'users/auth_user.html', context=context)

def register_view(request):
    if request.method == 'POST':
        form = RegisterForm(request.POST)
        if form.is_valid():
            user = form.save()
            slug = form.cleaned_data.get('username')
            city = form.cleaned_data.get('city')
            school = form.cleaned_data.get('school')
            grade = form.cleaned_data.get('grade')
            Profile.objects.create(user=user, slug=slug, city=city, school=school, grade=grade)
            username = form.cleaned_data.get('username')
            raw_password = form.cleaned_data.get('password1')
            user = authenticate(username=username, password=raw_password)
            login(request, user)
            return redirect('/')
        else:
            context = {'form': form, 'title': 'регистранция пользователя'}
            return render(request, 'users/reg_user.html', context=context)
    else:
        form = RegisterForm()
        context = {'form': form, 'title': 'регистрация пользователя'}
        return render(request, 'users/reg_user.html', context=context)

class ProfileUpdate(UpdateView):
    model = Profile
    template_name = 'users/profile_update.html'
    fields = ('city', 'school', 'grade', 'tests',)
    context_object_name = 'profile'

    def get_success_url(self):
        return reverse_lazy("users:profile", kwargs={'slug': self.object.slug})

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'Редактирование профиля'
        return context

lesson7+/templates/users/auth_user.html
{% extends "base.html" %}

{% block title %} {{title}} {% endblock%}

{% block content%}
<h1>Авторизация пользователя {{profile.user.first_name}} {{profile.user.last_name}}</h1>
<form action="" method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Войти</button>
    <button type="reset">Очистить</button>
</form>

{% endblock%}

lesson7+/templates/users/profile.html
{% extends "base.html" %}

{% block title %} {{title}} {% endblock%}

{% block content%}
    <h1>Профиль пользователя {{profile.user.first_name}} {{profile.user.last_name}}</h1>
    <p>Город: {{profile.city}}</p>
    <p>Школа: {{profile.school}}</p>
    <p>Класс: {{profile.grade}}</p>
    <div>
        <ol>
            <h4>Список тестов:</h4>
            {% for test in profile.tests.all %}
            <li><a href="{% url 'edu:detail_test' pk=test.pk %}">{{test}}</a></li>
            {% endfor %}
        </ol>
    </div>
    <a href="{% url 'users:profile_update' slug=profile.slug %}">Редактировать профиль</a>
{% endblock%}

lesson7+/templates/users/profile_update.html
{% extends "base.html" %}

{% block title %} {{title}} {% endblock%}

{% block content%}
<h1>Редактирование профиля пользователя {{profile.user.first_name}} {{profile.user.last_name}}</h1>
<form action="" method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Обновить</button>
    <button type="reset">Сбросить изменения</button>
</form>
<form action="{% url 'users:profile' slug=request.user.username %}"><button type="submit">Отменить</button></form>
{% endblock%}

lesson7+/templates/users/reg_user.html
{% extends "base.html" %}

{% block title %} {{title}} {% endblock%}

{% block content%}
<h1>Регистрация пользователя {{profile.user.first_name}} {{profile.user.last_name}}</h1>
<form action="" method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Зарегистрироваться</button>
    <button type="reset">Очистить</button>
</form>
{% endblock%}