lesson7+/core/urls.py
from django.urls import path
from core import views

app_name = 'core'


urlpatterns = [
    path('', views.NewList.as_view(), name='list_news'),
    path('new/<int:pk>', views.NewDetail.as_view(), name='detail_new'),
    path('about/', views.about, name='about'),
    path('new_create/', views.NewCreate.as_view(), name='new_create'),
    path('new_update/<int:pk>', views.NewUpdate.as_view(), name='new_update'),
    path('new_delete/<int:pk>', views.NewDelete.as_view(), name='new_delete'),
]

lesson7+/edu/urls.py
from django.urls import path
from edu import views


app_name = 'edu'


urlpatterns = [
    path('list_tests/', views.TestList.as_view(), name='list_tests'),
    path('list_tasks/', views.TaskList.as_view(), name='list_tasks'),
    path('test/<int:pk>', views.TestDetail.as_view(), name='detail_test'),
    path('task/<int:pk>', views.TaskDetail.as_view(), name='detail_task'),
    path('task_create/', views.TaskCreate.as_view(), name='task_create'),
    path('task_update/<int:pk>', views.TaskUpdate.as_view(), name='task_update'),
    path('task_delete/<int:pk>', views.TaskDelete.as_view(), name='task_delete'),
    path('test_create/', views.TestCreateView.as_view(), name='test_create'),
]

lesson7+/project/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('core.urls'), name='core'),
    path('edu/', include('edu.urls'), name='edu'),
    path('users/', include('users.urls'), name='users'),
]

lesson7+/core/models.py
from django.db import models
from django.contrib.auth.models import User

class Commit(models.Model):
    user = models.ForeignKey(User, null=True, blank=True, on_delete=models.PROTECT, verbose_name='Автор')
    user_name = models.CharField(max_length=20, blank=True, default='Аноним', verbose_name='Имя автора')
    description = models.TextField(default='', verbose_name='Комментарий')
    new = models.ForeignKey('New', on_delete=models.CASCADE, verbose_name='Новость')

    def __str__(self):
        return f'Комментарий от {self.user_name} к {self.new}'

    class Meta:
        verbose_name = 'Комментарий'
        verbose_name_plural = 'Комментарии'


class New(models.Model):
    title = models.CharField(max_length=1000, verbose_name='Название')
    description = models.TextField(default='', verbose_name='Описание')
    publish = models.BooleanField(default=False, verbose_name='Опубликованно')
    time_create = models.DateTimeField(auto_now_add=True, verbose_name='Создана')
    time_update = models.DateTimeField(auto_now=True, verbose_name='Отредактированно')

    def cnt_commit(self):
        return len(Commit.objects.filter(new=self))

    def __str__(self):
        return f'{self.title}'

    class Meta:
        verbose_name = 'Новость'
        verbose_name_plural = 'Новости'

lesson7+/core/views.py
from django.shortcuts import render
from django.urls import reverse_lazy
from django.views.generic import ListView, DetailView, UpdateView, CreateView, DeleteView

from core.models import New, Commit


def about(request):
    return render(request=request, template_name='core/about.html')


class TitleMixin():
    title = None

    def get_title(self):
        return self.title

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = self.get_title()
        return context


class NewList(TitleMixin, ListView):
    model = New
    template_name = 'core/list_news.html'
    context_object_name = 'news'
    title = 'Новости'


class NewDetail(DetailView):
    model = New
    template_name = 'core/detail_new.html'
    context_object_name = 'new'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = context['object'].title
        return context

class NewCreate(TitleMixin, CreateView):
    model = New
    template_name = 'core/new_create.html'
    fields = '__all__'
    title = 'Создание новости'
    success_url = reverse_lazy("core:list_news")


class NewUpdate(TitleMixin, UpdateView):
    model = New
    template_name = 'core/new_update.html'
    fields = '__all__'
    title = 'Редактирование новости'
    def get_success_url(self):
        return reverse_lazy("core:detail_new", kwargs={'pk': self.object.pk})


class NewDelete(TitleMixin, DeleteView):
    model = New
    template_name = 'core/new_delete.html'
    title = 'Удаление новости'
    success_url = reverse_lazy("core:list_news")

lesson7+/templates/core/about.html
{% extends "base.html" %}

{% load static %}

{% block title %} О себе {% endblock%}

{% block content%}
    <div class="group1">
        <img class="foto" src="{% static 'image/sally.jpg' %}" alt="Салли">
        <ul class="list-unstyled">
            <li><h1>Sally</h1></li>
            <li><h3>Старший страшила</h3></li>
            <li>Данные сотрудника
                <ul>
                    <li>Адресс: г. Монстратоун ул. Первая ужастная д. 14</li>
                    <li>Телефон: +0 999 666 66 66</li>
                    <li>E-mail: sally@monsters.com</li>
                </ul>
            </li>
            <li>
                <p>Заслуженный работник корпорации монстров, ас в запугивании, идет на рекорд по количеству добытой энергии крика. Напарник и верный друг Майка. Обаятелен, чувствителен, отважен и даже слегка безбашенн, несмотря на внешнюю страшильность иногда бывает безобидней котенка.</p>
                <p>Является потомственным страшилой, его отец был легендарным страшилой. Салли и Майк познакомились в Университете Монстров, в котором Салли хоть и производил впечатление страшилы, откровенно не хотел учиться, боялся не оправдать своей фамилии. Был исключен из Университета Монстров за неуспеваемость, после этого вместе с Майком бросил вызов декану факультета запугивания, и учавствовал в чемпионате страшил, среди "нестрашных" монстров. Сжульничал, подстроив все так, чтобы Майк проходил испытание на тренажере на самом низком уровне сложности. Был исключен вторично, однако вместе с Майком поступил в корпорацию монстров сортировщиком почты, где быстро прошагал карьерный путь до страшилы. Страшила, которому удалось запугать взрослых, чем он произвел впечатление даже на декана Терзалес.</p>
            </li>
        </ul>
    </div>
{% endblock%}

lesson7+/templates/core/detail_new.html
{% extends "base.html" %}

{% block title %} {{title}} {% endblock%}

{% block content%}
    {% if new %}
        <div>
            <p>{{new.title}}</p>
            <p>{{new.description}}</p>
        </div>
    {% else %}
        <div>
            <p>Что то пошло не так, вернитесь к новостям</p>
        </div>
    {% endif %}

    <div>
        {% if request.user.is_superuser %}
        <a href="{% url 'core:new_update' pk=new.pk%}">Обновить новость</a>
        <a href="{% url 'core:new_delete' pk=new.pk%}">Удалить новость</a>
        {% endif %}
        <a href="{% url 'core:list_news' %}">Назад к новостям</a>
    </div>
{% endblock%}

lesson7+/templates/core/list_news.html
{% extends "base.html" %}

{% block title %} {{title}} {% endblock%}

{% block content%}
    {% for new in news %}
        <p><a href="{% url 'core:detail_new' pk=new.pk %}">{{new}}</a></p>
        <p>{{new.description}}</p>
        <p>Опубликована: {{new.time_create}}</p>
    {% empty %}
        <p>пока новостей нет</p>
    {% endfor %}

    {% if request.user.is_superuser %}
        <a href="{% url 'core:new_create' %}">Добавить новость</a>
    {% endif %}

{% endblock%}

lesson7+/templates/core/new_create.html
{% extends "base.html" %}

{% block title %} {{title}} {% endblock%}

{% block content%}
<form action="" method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Сохранить</button>
    <button type="reset">Очистить</button>
</form>
<form action="{% url 'core:list_news' %}"><button type="submit">Отменить</button></form>
{% endblock%}

lesson7+/templates/core/new_delete.html
{% extends "base.html" %}

{% block title %} {{title}} {% endblock%}

{% block content%}
<form action="" method="post">
    {% csrf_token %}
    {{ form }}
    <p>Вы действительно хотите удалить {{new}}</p>
    <button type="submit">Удалить</button>
</form>
<form action="{% url 'core:list_news' %}"><button type="submit">Отменить</button></form>
{% endblock%}

lesson7+/templates/core/new_update.html
{% extends "base.html" %}

{% block title %} {{title}} {% endblock%}

{% block content%}
<form action="" method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Обновить</button>
    <button type="reset">Сбросить изменения</button>
</form>
<form action="{% url 'core:detail_new' pk=new.pk %}"><button type="submit">Отменить</button></form>
{% endblock%}